name: Build Docker Image
on: 
  push:
    branches:
    - master
env:
  DOCKER_CLI_EXPERIMENTAL: enabled
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build the Docker container image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/mediver:latest
      working-directory: mediver-server

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      working-directory: mediver-server

    - name: Push the image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mediver:latest
      working-directory: mediver-server
